esprit_caddy_homepage:
    path:     /
    defaults: { _controller: EspritCaddyBundle:Default:index }
esprit_caddy_homepage:
    path:     /affichage
    defaults: { _controller: EspritCaddyBundle:Caddy:affichage }
